name: fake_store
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  get: 4.6.6
  http: ^1.2.0
  intl: 0.19.0
  lottie: ^3.2.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  adaptive_icon_background: "#F2F2F2"
  image_path: assets/images/logo.png
  android: true
  ios: true
  min_sdk_android: 21

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/lottie/
  uses-material-design: true

  fonts:
    - family: EncodeSans
      fonts:
        - asset: assets/fonts/EncodeSans-Bold.ttf
        - asset: assets/fonts/EncodeSans-Regular.ttf
        - asset: assets/fonts/EncodeSans-Medium.ttf
        - asset: assets/fonts/EncodeSans-Light.ttf
